spring:
  application:
    name: doctor-service

  datasource:
    url: ${DOCTOR_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: optional:configserver:http://localhost:8888

jwt:
  secret: ${JWT_SECRET}
  expiration_time: ${JWT_EXPIRATION_TIME}

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
